### ISSUE TITLE
Rename repo & builds

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/mpox#168]
### Context
[General naming recommendations](https://www.who.int/news/item/28-11-2022-who-recommends-new-name-for-monkeypox-disease) are continuing to depreciate (and expected to depreciate further) using 'monkeypox'. We likely should replace 'monkeypox' with 'MPXV' (and possibly Mpox in some places). This will require:

- [x] Institute redirects for the URLS for all builds
    - [Slack thread](https://bedfordlab.slack.com/archives/C03G8HQEV18/p1695508115055009)
    - https://github.com/nextstrain/nextstrain.org/pull/712
    - https://github.com/nextstrain/nextstrain.org/pull/713
- [x] Replace all 'visible' links (where we write out URLS for files & similar) in docs & text (such as description)
    - #165
    - #169
    - #171
- [x] Rename the repo (GitHub should take care of redirects as long as a new repo `nextstrain/monkeypox` isn't created)
- [x] Update old repo name references
    - #220
    - https://github.com/nextstrain/augur/pull/1330
    - https://github.com/nextstrain/docker-base/pull/191
    - https://github.com/nextstrain/conda-base/pull/46
- [x] Update files on S3
    - Upload with `mpox` in path: #220
    - Add a redirect for old paths?
        - [Slack mention](https://bedfordlab.slack.com/archives/C03G8HQEV18/p1695313355846949?thread_ts=1695235467.547419&cid=C03G8HQEV18)
        - More discussion happening in #220
        - [Done](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1698867258722699) by @joverlee521

**Comment by victorlin** [comment]
Lots of progress here - I've updated the task list. @corneliusroemer is there anything else you can think of?

**Comment by corneliusroemer** [comment]
I think that sounds good. Next step would be repo rename? Let's do it one at a time to be able to know what broke it in case something breaks

**Comment by victorlin** [comment]
@corneliusroemer sounds good! Would you be able to do that whenever's good for you to monitor breakage? I'll be signing off soon and will be busy most of tomorrow.

**Comment by victorlin** [comment]
Also, this effort has shifted to use `mpox` instead of `mpxv` based on @trvrb's reasoning [in Slack](https://bedfordlab.slack.com/archives/C03G8HQEV18/p1692140142776189):

> I prefer `mpox` mainly because we've tended to use common names for viruses rather than the acronyms, eg `ebola` rather than `ebov`, `zika` rather than `zikv`, `mumps` rather than `MuV`, `dengue` rather than `denv`.

**Comment by victorlin** [comment]
Repo rename done by @trvrb ([Slack thread](https://bedfordlab.slack.com/archives/C03G8HQEV18/p1698858215817239)).

**Comment by victorlin** [comment]
I updated the task list in the issue description, and I think everything is done here. Please re-open if you notice anything that was missed.
