### ISSUE TITLE
ingest: Automated workflow failing during fetch from NCBI

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/mpox#285]
_Blocked by upstream issue: https://github.com/ncbi/datasets/issues/419_

Failed during [automated ingest on 2024-10-31](https://github.com/nextstrain/mpox/actions/runs/11616507084/job/32349642389#step:5:366).

```
[batch] [2024-10-31T17:11:13+00:00] Error: Download error: stream error: stream ID 3; INTERNAL_ERROR; received from peer
```

I manually re-ran the workflow thinking it was a transient error, but it [hit the same error](https://github.com/nextstrain/mpox/actions/runs/11616507084/job/32352906602#step:5:389).

```
[batch] [2024-10-31T18:19:14+00:00] Error: Download error: stream error: stream ID 3; INTERNAL_ERROR; received from peer
```

Then realized this was already reported as an error in https://github.com/ncbi/datasets/issues/419.

**Comment by corneliusroemer** [comment]
Unblocked probably, at least in my tests

**Comment by joverlee521** [comment]
The automated ingest hit the error again [yesterday](https://github.com/nextstrain/mpox/actions/runs/11653159899/job/32445253796#step:5:389), but seems to be running fine [today](https://github.com/nextstrain/mpox/actions/runs/11669088861)

**Comment by joverlee521** [comment]
Ingest failed [yesterday](https://github.com/nextstrain/mpox/actions/runs/11822194686/attempts/1) and [today](https://github.com/nextstrain/mpox/actions/runs/11842020062) with the same error again.

**Comment by corneliusroemer** [comment]
Yeah I already reported (reopened my old issue) over at their Github issue tracker

**Comment by joverlee521** [comment]
[Ingest completed successfully today](https://github.com/nextstrain/mpox/actions/runs/11860405342)
