### ISSUE TITLE
annotate mutations between the inferred root and the reference sequence

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/mpox#296]
Feature request via WA-DoH (via [slack](https://bedfordlab.slack.com/archives/C01G4B4UY31/p1730391930819899)): annotating mutations between the inferred root and the reference sequence is necessary for datasets to be used within Nextclade. Without this the masking leads to a the inferred root sequence having large runs of `A`s which lead to incorrect mutations called against new sequences within Nextclade.

Adding a config flag which allows workflows to toggle this on/off is a solution. 

Here's a diff of the changes (without the ability for a config to modulate this):
```diff
--- a/phylogenetic/rules/annotate_phylogeny.smk
+++ b/phylogenetic/rules/annotate_phylogeny.smk
@@ -27,6 +27,7 @@ rule ancestral:
     input:
         tree=build_dir + "/{build_name}/tree.nwk",
         alignment=build_dir + "/{build_name}/masked.fasta",
+        reference=config["reference"],
     output:
         node_data=build_dir + "/{build_name}/nt_muts.json",
     params:
@@ -36,6 +37,7 @@ rule ancestral:
         augur ancestral \
             --tree {input.tree} \
             --alignment {input.alignment} \
+            --root-sequence {input.reference} \
             --output-node-data {output.node_data} \
             --inference {params.inference}
         """
```

**Comment by joverlee521** [comment]
> Adding a config flag which allows workflows to toggle this on/off is a solution.

I can add the config option to make this togglable in the workflow. 

However, it's not clear to me if we need to be using this option for Nextstrain builds to support Nextclade use when the official Nextclade datasets already exist.

I just checked and the core [all-clades build](https://nextstrain.org/mpox/all-clades) errors out on Nextclade

![Screenshot 2024-11-20 at 3 35 16 PM](https://github.com/user-attachments/assets/c864a8d8-61d8-41e0-ba24-62f4afee6701)

and the core [clade-IIb build](https://nextstrain.org/mpox/clade-IIb) shows the extra mutations

![Screenshot 2024-11-20 at 3 37 24 PM](https://github.com/user-attachments/assets/539a6454-de5e-4421-a55d-45939a97fe3c)

**Comment by DOH-SML1303** [comment]
Hello! While I'm trying to maintain a WA-focused mpox build, I was wondering if you had an ETA for when this feature would be available? I don't think we need to rush; I'm just trying to figure out the best way to be able to keep the changes we made to the snakefile while also being able to pull new changes in order to maintain the build while we wait for this feature to become available

**Comment by joverlee521** [comment]
Hey @DOH-SML1303, I've made the changes in https://github.com/nextstrain/mpox/pull/297. I'll wait for feedback and will most likely merge it later next week.

**Comment by DOH-SML1303** [comment]
Sounds good, thank you so much!

**Comment by joverlee521** [comment]
Hi @DOH-SML1303, the PR has been merged! If you pull down the latest `master` branch, you can use the `ancestral_root_seq` config param to specify the root sequence file to pass to `augur ancestral`. 

Here is an example in the CI workflow config: 
https://github.com/nextstrain/mpox/blob/02f660a2616bede159ede64a0ee8edf86a27702f/phylogenetic/build-configs/ci/config.yaml#L4-L5

**Comment by DOH-SML1303** [comment]
Hi @joverlee521, amazing! Thank you so much. I will pull this down and run the build this week and let you know if I have any problems. I appreciate you all working on this!
